### ISSUE TITLE
Замена mail()

### ISSUE THREAD

**Issue by mihdan** [cloudpayments/CloudPayments_WooCommerce#1]
В ядре WordPress встроена функция `wp_mail()` для отправки почты со своими настройками и хуками

**Comment by cloudpayments** [comment]
Привет.
Подскажите, а в каком месте стоит использовать эту функцию?

**Comment by mihdan** [comment]
Например, [тут](https://github.com/cloudpayments/CloudPayments_WooCommerce/blob/master/woocommerce-cloudpayments/wc-gateway-cloudpayments.php#L191)

**Comment by cloudpayments** [comment]
fix

**Comment by mihdan** [comment]
Всего 4 года прошло)
