### ISSUE TITLE
(README.md) Receipt уведомление

### ISSUE THREAD

**Issue by serednitsky** [cloudpayments/CloudPayments_WooCommerce#16]
**Заменить:**
Receipt Уведомление (Уведомление об онлайн-чеке):
https://domen.ru/wc-api/wc_cloudpayments_gateway?action==receipt

**На:** 
Receipt Уведомление (Уведомление об онлайн-чеке):
https://domen.ru/wc-api/wc_cloudpayments_gateway?action=receipt

**Comment by cloudpayments** [comment]
fixed

**Comment by cloudpayments** [comment]
final
