### ISSUE TITLE
Ошибка 3006

### ISSUE THREAD

**Issue by Teniana** [cloudpayments/CloudPayments_WooCommerce#9]
Подскажите, в чем может быть проблема - внезапно перестали проходить платежи, пользователю приходит отказ. В личном кабинете код транзакции отображается как 3006. В настройках сайта check не меняли - domain/wc-api/wc_cloudpayments?action=check

![photo_2021-07-27_18-52-36](https://user-images.githubusercontent.com/61711393/127192980-49115bd5-e576-44e6-9bda-a82ea4795054.jpg)

**Comment by cloudpayments** [comment]
Вам нужно обновить адреса для уведомлений. Новые можете увидеть в настройках платежки (модуля)
